name: Build Locus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Locus for iOS
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Clone Locus repository
        run: |
          git clone https://github.com/Myzel394/locus.git
      - name: Build Locus
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          sudo xcodebuild -license accept && xcodebuild -downloadPlatform iOS
          cd locus && flutter config --no-analytics && flutter --disable-telemetry && flutter build ipa --no-codesign && cd $WORKSPACE
      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: locus
      - name: Create .ipa
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          cd locus && cd build && cd ios && cd archive && cd Runner.xcarchive && cd Products
          mv ./Applications ./Payload
          zip -vr Locus.zip Payload -x "*.DS_Store"
          mv ./Locus.zip $WORKSPACE/Locus.ipa
          ls -la $WORKSPACE
      - name: Upload Locus.ipa
        uses: actions/upload-artifact@v4
        with:
          name: Locus
          path: Locus.ipa
