name: Build Locus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Locus for iOS
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Clone Locus repository
        run: |
          git clone https://github.com/Myzel394/locus.git
      - name: Build Locus
        run: |
          sudo xcodebuild -license accept && xcodebuild -downloadPlatform iOS
          cd locus && flutter config --no-analytics && flutter --disable-telemetry && flutter build ipa --no-codesign
      - name: Upload .xcarchive
        with:
          name: Runner.xcarchive
          path: locus/build/ios/archive/Runner.xcarchive
      
